import { StyleSheet } from 'react-native';

const styles = StyleSheet.create({
  authContainer: { flex: 1, backgroundColor: '#4a90e2' },
  authContent: { flex: 1, justifyContent: 'center', padding: 20 },
  authHeader: { alignItems: 'center', marginBottom: 40 },
  authLogo: { fontSize: 80, marginBottom: 10 },
  authTitle: { fontSize: 28, fontWeight: 'bold', color: '#fff', marginBottom: 5 },
  authSubtitle: { fontSize: 16, color: '#fff', opacity: 0.9 },
  authForm: { backgroundColor: '#fff', borderRadius: 20, padding: 25 },
  formLabel: { fontSize: 14, fontWeight: '600', color: '#333', marginBottom: 8 },
  authInput: { backgroundColor: '#f5f7fa', borderRadius: 10, paddingHorizontal: 15, paddingVertical: 12, marginBottom: 15, fontSize: 16 },
  codeInput: { fontSize: 24, fontWeight: 'bold', textAlign: 'center', letterSpacing: 10 },
  authButton: { backgroundColor: '#4a90e2', borderRadius: 10, paddingVertical: 15, alignItems: 'center', marginTop: 10 },
  authButtonText: { color: '#fff', fontSize: 16, fontWeight: 'bold' },
  buttonDisabled: { opacity: 0.6 },
  backLink: { marginTop: 15, alignItems: 'center' },
  backLinkText: { color: '#666', fontSize: 14 },
  container: { flex: 1, backgroundColor: '#f5f7fa' },
  header: { backgroundColor: '#4a90e2', padding: 20, flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  headerTitle: { fontSize: 24, fontWeight: 'bold', color: '#fff' },
  logoutButton: { backgroundColor: '#e74c3c', paddingHorizontal: 15, paddingVertical: 8, borderRadius: 8 },
  logoutButtonText: { color: '#fff', fontWeight: '600', fontSize: 14 },
  userInfo: { backgroundColor: '#3a7bc8', paddingHorizontal: 20, paddingVertical: 10 },
  userInfoText: { color: '#fff', fontSize: 13, fontWeight: '500' },
  navigation: { flexDirection: 'row', backgroundColor: '#fff', borderBottomWidth: 1, borderBottomColor: '#e0e0e0' },
  navButton: { flex: 1, paddingVertical: 12, alignItems: 'center' },
  navButtonActive: { backgroundColor: '#4a90e2', borderBottomWidth: 3, borderBottomColor: '#2e5c8a' },
  navButtonIcon: { fontSize: 24, marginBottom: 4 },
  navButtonText: { fontSize: 11, fontWeight: '600', color: '#666' },
  navButtonTextActive: { color: '#fff' },
  content: { flex: 1, padding: 15 },
  screenHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 15 },
  screenTitle: { fontSize: 22, fontWeight: 'bold', color: '#333', marginBottom: 10 },
  addListButton: { backgroundColor: '#27ae60', paddingHorizontal: 15, paddingVertical: 10, borderRadius: 8 },
  addListButtonText: { color: '#fff', fontWeight: '600', fontSize: 14 },
  listContainer: { width: 320, backgroundColor: '#e8ecef', borderRadius: 12, padding: 15, marginRight: 15, height: 550 },
  listHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 10 },
  listTitle: { fontSize: 18, fontWeight: 'bold', color: '#333' },
  listAddButton: { backgroundColor: '#4a90e2', borderRadius: 20, padding: 5 },
  listAddButtonText: { color: '#fff', fontSize: 18, fontWeight: 'bold' },
  taskList: { flex: 1 },
  taskCard: { backgroundColor: '#fff', borderRadius: 10, padding: 15, marginBottom: 12, borderLeftWidth: 6 },
  taskHeader: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center', marginBottom: 8 },
  taskTitle: { fontSize: 16, fontWeight: 'bold', color: '#333' },
  taskTitleCompleted: { textDecorationLine: 'line-through', color: '#999' },
  taskDescription: { fontSize: 14, color: '#666', marginBottom: 8 },
  deadlineBadge: { alignSelf: 'flex-start', borderRadius: 12, paddingHorizontal: 10, paddingVertical: 4, marginBottom: 8 },
  deadlineText: { fontSize: 12, fontWeight: '600' },
  taskResponsible: { fontSize: 13, color: '#555', marginBottom: 8 },
  completeButton: { backgroundColor: '#27ae60', borderRadius: 8, paddingVertical: 6, alignItems: 'center' },
  completeButtonText: { color: '#fff', fontWeight: '600' },
  completedBadge: { backgroundColor: '#e0e0e0', borderRadius: 8, paddingVertical: 6, alignItems: 'center' },
  completedText: { color: '#666', fontWeight: '600' },
  chatMessages: { flex: 1, marginBottom: 10 },
  chatEmpty: { flex: 1, justifyContent: 'center', alignItems: 'center', marginTop: 50 },
  chatEmptyTitle: { fontSize: 24, fontWeight: 'bold', color: '#333', marginBottom: 10 },
  chatEmptySubtitle: { fontSize: 16, color: '#666' },
  chatBubble: { maxWidth: '80%', borderRadius: 15, padding: 10, marginVertical: 5 },
  chatBubbleUser: { backgroundColor: '#4a90e2', alignSelf: 'flex-end', borderTopRightRadius: 0 },
  chatBubbleBot: { backgroundColor: '#e0e0e0', alignSelf: 'flex-start', borderTopLeftRadius: 0 },
  chatText: { fontSize: 16 },
  chatTextUser: { color: '#fff' },
  chatTextBot: { color: '#333' },
  chatInputContainer: { flexDirection: 'row', alignItems: 'center' },
  chatInput: { flex: 1, backgroundColor: '#fff', borderRadius: 25, paddingHorizontal: 15, paddingVertical: 10, fontSize: 16, borderWidth: 1, borderColor: '#ccc' },
  chatSendButton: { marginLeft: 10, backgroundColor: '#4a90e2', borderRadius: 25, padding: 12 },
  chatSendButtonText: { color: '#fff', fontSize: 18, fontWeight: 'bold' },
  statsGrid: { flexDirection: 'row', flexWrap: 'wrap', justifyContent: 'space-between' },
  statCard: { width: '48%', borderRadius: 12, padding: 20, marginBottom: 15, alignItems: 'center' },
  statIcon: { fontSize: 30, marginBottom: 10 },
  statNumber: { fontSize: 28, fontWeight: 'bold', color: '#333' },
  statLabel: { fontSize: 14, color: '#666' },
  modalOverlay: { flex: 1, backgroundColor: 'rgba(0,0,0,0.5)', justifyContent: 'center', alignItems: 'center' },
  modalContent: { width: '90%', backgroundColor: '#fff', borderRadius: 12, padding: 20 },
  modalTitle: { fontSize: 20, fontWeight: 'bold', color: '#333', marginBottom: 15, textAlign: 'center' },
  input: { backgroundColor: '#f5f7fa', borderRadius: 10, paddingHorizontal: 15, paddingVertical: 12, marginBottom: 15, fontSize: 16 },
  textArea: { height: 80, textAlignVertical: 'top' },
  modalButtons: { flexDirection: 'row', justifyContent: 'space-between' },
  modalButton: { flex: 1, paddingVertical: 12, borderRadius: 8, alignItems: 'center', marginHorizontal: 5 },
  modalButtonPrimary: { backgroundColor: '#4a90e2' },
  modalButtonTextPrimary: { color: '#fff', fontWeight: '600' },
  modalButtonSecondary: { backgroundColor: '#e0e0e0' },
  modalButtonTextSecondary: { color: '#333', fontWeight: '600' },
});

export default styles;